## Introduction to Prediction using Surnames Analysis

### Hypothesis
To relate a name to nationality, check for the most common letter combinations/pronounciations within a specific language that makes it unique.

For example:
- 'ch' like in __mich__ or __dich__
- 'sch' like in  __Tisch__
- 'tsch' like in __Deutsch__
- 'aus' like in __Haus__ or __Gasthaus__


Note: This is a naïve approach. There will be room to improve later!

In [1]:
import pandas as pd

In [2]:
def is_arabic(word):
    if "afa" in word:
        return True
    elif "ba" in word:
        return True
    elif "zay" in word:
        return True
    elif "shin" in word:
        return True
    elif "ra" in word:
        return True
    elif "sud" in word:
        return True
    elif "alif" in word:
        return True
    elif "aa" in word:
        return True
    elif "aha" in word:
        return True
    elif "dh" in word:
        return True
    elif "tha" in word:
        return True
    elif "slah" in word:
        return True
    elif "att" in word:
        return True
    elif "kh" in word:
        return True
    elif "zog" in word:
        return True
    elif "tar" in word:
        return True
    elif "eeb" in word:
        return True
    elif "alb" in word:
        return True
    elif "haj" in word:
        return True
    else:
        return False

In [3]:
def is_chinese(word):
    if len(word) < 4:
        return True
    elif "ang" in word:
        return True
    elif "iang" in word:
        return True
    elif "ing" in word:
        return True
    elif "eng" in word:
        return True
    elif "sen" in word:
        return True
    elif "ong" in word:
        return True
    elif "hao" in word:
        return True
    elif "aw" in word:
        return True
    elif "eah" in word:
        return True
    else:
        return False

In [4]:
def is_czech(word):
    if "mak" in word:
        return True
    elif "tak" in word:
        return True
    elif "erv" in word:
        return True
    elif "fk" in word:
        return True
    elif "som" in word:
        return True
    elif "iova" in word:
        return True
    elif "perer" in word:
        return True
    elif "nek" in word:
        return True
    elif "esi" in word:
        return True
    elif "ovic" in word:
        return True
    elif "nec" in word:
        return True
    elif "zka" in word:
        return True
    elif "abb" in word:
        return True
    elif "enk" in word:
        return True
    elif "chek" in word:
        return True
    elif "ss" in word:
        return True
    elif "erka" in word:
        return True
    elif "kovsky" in word:
        return True
    elif "gl" in word:
        return True
    elif "ovy" in word:
        return True
    elif "pp" in word:
        return True
    elif "jj" in word:
        return True
    elif "lik" in word:
        return True
    elif "sk" in word:
        return True

In [5]:
def is_dutch(word):
    if "eter" in word:
        return True
    elif "aijer" in word:
        return True
    elif "oorn" in word:
        return True
    elif "hren" in word:
        return True
    elif "rik" in word:
        return True
    elif "ogt" in word:
        return True
    elif "eeu" in word:
        return True
    elif "man" in word:
        return True
    elif "aar" in word:
        return True
    elif "ijk" in word:
        return True
    elif "eghe" in word:
        return True
    elif "del" in word:
        return True
    elif "kk" in word:
        return True
    elif "seg" in word:
        return True
    elif "ning" in word:
        return True
    elif "sch" in word:
        return True
    elif "ken" in word:
        return True
    return False

In [6]:
def is_german(word):
    word = word.lower()
    keys = "äöü"
    for letter in word:
        if letter in keys:
            return True
        
    if "isch" in word:
        return True
    if "tsch" in word:
        return True
    if "aus" in word:
        return True
    return False

In [7]:
def is_italian(word):
    """Naive Italian Surname Identification"""
    return word.count("i") >= 3

In [8]:
def is_japanese(word):
    """Naive Japanese Surname Identification"""
    if "naka" in word:
        return True
    elif "tsu" in word:
        return True
    elif "kawa" in word:
        return True
    else:
        return False

In [9]:
def is_spanish(word):
    """Naive Spanish Surname Identification"""
    word = word.lower()
    keys = "áéíóúüñ"
    for letter in word:
        if letter in keys:
            return True
    return False

In [10]:
"""
    Naive Nationality Identification

    Returns "Unknown" for nationalities that are detected as 
    other than Spanish, Italian or Japanese
"""

def check_nationality(surname):
    
    if is_arabic(surname):
        return "Arabic"
    
    if is_chinese(surname):
        return "Chinese"
    
    if is_czech(surname):
        return "Czech"
    
    if is_dutch(surname):
        return "Dutch"
    
    if is_german(surname):
        return "German"
    
    if is_italian(surname):
        return "Italian"
    
    if is_japanese(surname):
        return "Japanese"
    
    if is_spanish(surname):
        return "Spanish"
    
    return "Unknown"

In [11]:
# read the csv file into data frame.
def read_file(file_name):
    df = pd.read_csv(file_name, index_col = None)
    print("Preview of original file:")
    print(df.head())
    
    return df

In [12]:
# read first column only
def modify_file(df):
    surname_list = pd.DataFrame(df[df.columns[0]])
    surname_list.rename(columns = {'Unnamed: 0':'surname'}, inplace = True)
    
    return surname_list

In [13]:
# retrieve nationality for each name.
def insert_nationality_pred(surname_list):
    nationality = []
    col = "surname"
    for name, row in surname_list.iterrows():
        nationality.append(check_nationality(row[col]))

    surname_list.insert(1, "nationality", nationality, True)
    
    return surname_list

In [14]:
# files to be predicted
surname_csv = "data_set/surnames-dev.csv"

df = read_file(surname_csv)
surname_list = modify_file(df)
pred_surnames = insert_nationality_pred(surname_list)

Preview of original file:
  Unnamed: 0 Unnamed: 1
0   Fakhoury     Arabic
1       Toma     Arabic
2      Koury     Arabic
3       Bata     Arabic
4     Samaha     Arabic

In [15]:
musician_csv = "data_set/musician_surnames.csv"
df = read_file(musician_csv)
surname_list = modify_file(df)
pred_mus_surnames = insert_nationality_pred(surname_list)

Preview of original file:
   Unnamed: 0 Unnamed: 1
0       Belén    Spanish
1  Cunningham   Scottish
2          Ji     Korean
3  Grönemeyer     German
4        Lévy     French

In [16]:
# ouput results
pred_surnames.to_csv("results/surname_results.csv", index=False)
pred_mus_surnames.to_csv("results/musician_results.csv", index=False)

## Results
### Surname List

In [17]:
pred_surnames

       surname nationality
0     Fakhoury      Arabic
1         Toma     Unknown
2        Koury     Unknown
3         Bata     Unknown
4       Samaha      Arabic
...        ...         ...
2998      Banh     Unknown
2999     Thach     Unknown
3000     Hoang     Chinese
3001        Do     Chinese
3002      Than     Unknown

[3003 rows x 2 columns]

## Musician Surnames

In [18]:
pred_mus_surnames

      surname nationality
0       Belén     Spanish
1  Cunningham     Chinese
2          Ji     Chinese
3  Grönemeyer      German
4        Lévy     Spanish
5      Sawano     Chinese
6         Yue     Chinese
7   Karadimos      Arabic
8   O'Riordan     Unknown
9     VIvaldi     Unknown

## Observations
### Most Likely Correct
1) Often Chinese last names tend to be 3 letters long. According to my algorithm, if the name is less than 3 letters long then it should fall into this category:
    Musician Surnames: "6: Yue" and "2: Ji"
    
2) Double j's (jj) show up frequently in Czech language. It's even use in slang texts. JJ mean "Jo Jo" which mean yes. In names, this combination also appears.
    Surnames List: "161: Hajjar" and "152: Najjar"

### Most Likely Incorrect
1) Japanese tends of have syllable pairs (sa-wa-no). I did not look for this, and so it was misidentified. Additionally, the system saw 'wan' and assumed it was Chinese. Musician Surname: 5. Sawano.

2) The name Isa (158) from surnames list was misidentified as Chinese as well. It should be Arabic. Going by the length of the name is not the best way to indicate the nationaility of the name as not all names that are less than 4 in length is Chinese.